services:
  rust-server:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: docker/rust.Dockerfile
    working_dir: /app
    volumes:
      - ./apps/rust-server:/app
    ports:
      - "3000:3000"